### PR TITLE
Fixing modal position & styling

### PR DESCRIPTION
**Pull request by Oluane**
## Description

This PR changes `ConfirmationBox` modals position (fully centered now) and their padding to fits mocks.

I added them a closing cross in upper right corner. To do so, I reused the `CrossIcon` SVG we already had for `alertMessages`, but I had to modify it a little. 

I changed its path attribute `fill` from hardcoded color (`#FFF`) to `currentColor` CSS variable, which means that it will now have the color defined by its parent element. It allows us, in case of monochromatic SVG, to use the same component for multiple case and color. What's your thoughts about this change ?

## Type of change

- [ ] **Chore** (non-breaking change which refactors / improves the existing code base).
- [x] **Bug fix** (non-breaking change which fixes an issue).
- [ ] **New feature** (non-breaking change which adds functionality).
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] My code follows the style [**contributing guidelines**][contributing_file] of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

[contributing_file]: https://github.com/fewlinesco/connect-account/blob/master/README.adoc

### CODE REVIEW

**Comment by Fenntasy** [comment]
Task linked: [CU-ff5vdz [refacto] - Fix modal position and style](https://app.clickup.com/t/ff5vdz)

**Comment by Fuzznimp** [comment]
> I changed its path attribute fill from hardcoded color (#FFF) to currentColor CSS variable, which means that it will now have the color defined by its parent element. It allows us, in case of monochromatic SVG, to use the same component for multiple case and color. What's your thoughts about this change ?

I think this is a really good find! I'm @Fenntasy in case you did not know :).

I've played a bit more with React Portals last night, we could use it for this case. We'll have to check the benefits of it (mostly independent CSS heritage). For now, this more than enough. Good job 🦾 .

One comment thought. Could you add some `border-radius` on the modal? Thanks!

**Comment by Oluane** [comment]
Yep, I forgot about `border-radius`, I added it 🙇

**Review by Fuzznimp — APPROVED** [review]

**Review by Fenntasy — APPROVED** [review]
👍

**Pull request merged**
