### PR TITLE
Remove renderprops on mark as primary flow

### PR DESCRIPTION
**Pull request by Oluane**
## Description

This PR goal is to remove the renderProps implementation on the mark an identity as primary flow, by relocating the logical function (which actually mark an identity as primary by making a call to Management) to its own workflow file, and no more in a business/display component approach.

The stories concerning the primary & delete modal were also updated.

## Type of change

- [x] **Chore** (non-breaking change which refactors / improves the existing code base).
- [ ] **Bug fix** (non-breaking change which fixes an issue).
- [ ] **New feature** (non-breaking change which adds functionality).
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

## How Has This Been Tested?

Manually + e2e test ran

## Checklist:

- [x] My code follows the style [**contributing guidelines**][contributing_file] of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.

[contributing_file]: https://github.com/fewlinesco/connect-account/blob/master/README.adoc

### CODE REVIEW

**Review by Fenntasy — COMMENTED** [review]
You made me expect tests in the previous PR 😁

**Comment by Oluane** [comment]
> You made me expect tests in the previous PR 😁

I wondered a little time if it was necessary since this is one of the only flow that has already a e2e test, then I decided it was not. Your thought about that ? 🙂

**Comment by Fenntasy** [comment]
> I wondered a little time if it was necessary since this is one of the only flow that has already an e2e test, then I decided it was not. Your thought about that ?

Will your e2e test the error cases?

**Comment by Oluane** [comment]
> Will your e2e test the error cases?

Nope, they will not. But this flow doesn't have specific error for now (I don't know if it will have some in the future 🤔 )

**Review by Fenntasy — APPROVED** [review]

**Pull request merged**
