### PR TITLE
Adding trailing slash

### PR DESCRIPTION
**Pull request by Fuzznimp**
## Description

This PR aims at adding a trailing slash at the end of our paths, as discussed with @Fenntasy in the past.
This feature should help with the intempestive redirections in the Lighthouse audits, as in CI, we get the URL from Heroku, and they always append a trailing slash:
```
// lighthouserc.js
url: [
        process.env.CONNECT_TEST_ACCOUNT_URL,
        `${process.env.CONNECT_TEST_ACCOUNT_URL}account/`,
        `${process.env.CONNECT_TEST_ACCOUNT_URL}account/profile/`,
        `${process.env.CONNECT_TEST_ACCOUNT_URL}account/profile/user-profile/new/`,
        `${process.env.CONNECT_TEST_ACCOUNT_URL}account/logins/`,
        `${process.env.CONNECT_TEST_ACCOUNT_URL}account/logins/email/new/`,
        `${process.env.CONNECT_TEST_ACCOUNT_URL}account/logins/phone/new/`,
        `${process.env.CONNECT_TEST_ACCOUNT_URL}account/security/`,
        `${process.env.CONNECT_TEST_ACCOUNT_URL}account/security/sudo/`,
        `${process.env.CONNECT_TEST_ACCOUNT_URL}account/locale/`,
      ],
```

**I verified that SWR was treating  `/` and `no-/` URLs the same in its cache, it automatically trim the `/`:**
image

## Type of change

- [x] **Chore** (non-breaking change which refactors / improves the existing code base).
- [ ] **Bug fix** (non-breaking change which fixes an issue).
- [ ] **New feature** (non-breaking change which adds functionality).
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

## Checklist

- [ ] My code follows the style [**contributing guidelines**][contributing_file] of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

[contributing_file]: https://github.com/fewlinesco/connect-account/blob/master/README.adoc

### CODE REVIEW

**Comment by frieda-ewlines** [comment]
Task linked: [CU-pzj68t Add trailing slash](https://app.clickup.com/t/pzj68t)

**Review by Fenntasy — DISMISSED** [review]
I'm happy to approve the PR but I need to warn that you need to be sure it works as intended everywhere (I had the displeasure of having it working good in production but not in dev environment or vice versa)

**Comment by Fuzznimp** [comment]
@Fenntasy I tried in dev env and in review app, both working great. Not sure how to test it in prod though 🤔.

**Review by Meyclem — DISMISSED** [review]

**Comment by Fenntasy** [comment]
> @Fenntasy I tried in dev env and in review app, both working great. Not sure how to test it in prod though 🤔.

Reviews should do the trick 👍

**Review by Oluane — APPROVED** [review]

**Pull request merged**
