### PR TITLE
Fix phone input verification

### PR DESCRIPTION
**Pull request by Fuzznimp**
## Description

This PR aim was to fix the phone input verification. While doing so, I stumble across a promising lib: https://www.npmjs.com/package/react-phone-number-input, which I decided to implement, as our previous phone input was — appart from the lack of internationalisation — terrible.

## Type of change

- [ ] **Chore** (non-breaking change which refactors / improves the existing code base).
- [ ] **Bug fix** (non-breaking change which fixes an issue).
- [x] **New feature** (non-breaking change which adds functionality).
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

## Issues

Some monkey testing highlighted some weird behaviour.

## List of added dependencies

- `react-phone-number-input`: "3.1.15"
- `@types/react-phone-number-input`: "3.0.6",

## Checklist:

- [x] My code follows the style [**contributing guidelines**][contributing_file] of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.

[contributing_file]: https://github.com/fewlinesco/connect-account/blob/master/README.adoc

### CODE REVIEW

**Review by Oluane — COMMENTED** [review]
So, we don't have any way to handle the "validity" of the phone number before redirecting to verification code flow for now ?

**Comment by Fuzznimp** [comment]
Well, I'm removing the checks from our side, as it is now done from `react-phone-number-input`. I will also remove the corresponding test, as it is tested in the lib.

**Comment by Oluane** [comment]
I mean, right now, if you type a french number with more numbers than it should have, and click on submit button, you get redirected to validation code page as if everything was ok. Do we plan to add some kind of checks (or implement the ones provided vy the lib, if there's any) to prevent this behaviour or not ?

**Comment by Fenntasy** [comment]
Task linked: [CU-bay6jn [fix] - Fix phone number input](https://app.clickup.com/t/bay6jn)

**Comment by Fuzznimp** [comment]
Closing this PR because the review app build is messed up.

**Pull request closed without merging**
